services:
  workspace:
    image: broyale/workspace:latest
    pull_policy: build
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME:-deno}
        USER_UID: ${USER_UID:-1993}
        USER_GID: ${USER_GID:-1993}
        TZ: ${TZ:-UTC}
        LANGUAGE: ${LANGUAGE:-en}
        COUNTRY: ${COUNTRY:-US}
        ENCODING: ${ENCODING:-UTF-8}
        LOCALE: ${LOCALE:-"en_US.UTF-8 UTF-8"}
    command: sleep infinity
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}
        target: /workspace
      - type: volume
        source: workspace-bashhistory
        target: /commandhistory

  dev.broyale.localhost:
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/packages/client-main
        target: /app

  field.broyale.localhost:
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/packages/server-field
        target: /app

volumes:
  workspace-bashhistory:
    driver: local
